# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ariff Azraai
tagline:          "Primitive Digital Native"
description:      "Personal home page. Don't go gentle into that goodnite."
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ariff Azraai'
  url:            http://azraai.me

paginate:         5
