# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ariff Azraai
tagline:          Primitive Digital Native
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ariff Azraai'
  url:            http://azraai.me

side:
  title:          Scribbles
  description:    "Personal home page, don't go gentle into that good night."

paginate:         5
